{
  "id": "unit_price",
  "capture": {
    "operator": "image_snapshot"
  },
  "perceive": {
    "operator": "ocr_raw"
  },
  "extract": {
    "operator": "compute",
    "price_schema": "price.yaml",
    "weight_schema": "weight.yaml",
    "min_confidence": 0.65
  },
  "respond": {
    "operator": "compute",
    "template": "compute.j2",
    "max_words": 35,
    "unit": "/100g",
    "reference_grams": 100,
    "unit_modes": {
      "metric": {
        "unit": "/100g",
        "reference_grams": 100
      },
      "imperial_oz": {
        "unit": "/oz",
        "reference_grams": 28.3495
      },
      "imperial_lb": {
        "unit": "/lb",
        "reference_grams": 453.592
      }
    },
    "unit_mode": "metric",
    "formula": "{price} / ({weight}/100)",
    "low_confidence_tip": "Tip: confirm both price and weight are visible.",
    "steady_message": "Confidence steady.",
    "missing_message": "Need price and weight"
  }
}
