{
  "id": "unit_price",
  "capture": {
    "operator": "image_snapshot"
  },
  "perceive": {
    "operator": "ocr_raw"
  },
  "extract": {
    "operator": "compute",
    "price_schema": "price.yaml",
    "weight_schema": "weight.yaml",
    "min_confidence": 0.65
  },
  "respond": {
    "operator": "compute",
    "template": "compute.j2",
    "max_words": 35,
    "unit": "/100g",
    "formula": "{price} / ({weight}/100)",
    "low_confidence_tip": "Tip: confirm both price and weight are visible.",
    "steady_message": "Confidence steady.",
    "missing_message": "Need price and weight"
  }
}
