name: UX Gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  handshake-budgets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Validate handshake timing budgets
        run: pytest tests/test_handshake_timing.py
